workflows:
  ios-workflow:
    name: IOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.ted.bosscitykeys